### ISSUE TITLE
Additional setup for github repo

### ISSUE THREAD

**Issue by cmungall** [alliance-genome/agr_schemas#11]
* Add a CONTRIBUTING.md, see for example: https://github.com/biolink/biolink-api/blob/master/CONTRIBUTING.md
 * Add a .travis.yml and configure this to validate the json schema for syntax errors. See for example [go-site travis](https://github.com/geneontology/go-site/blob/master/.travis.yml). We use kwalify rather than json-schema but same idea

**Comment by christabone** [comment]
@cmungall I deleted your issue-11 branch after merging your pull request. Sorry, did you still need it? Should have checked -- might have to re-push your local copy.

**Comment by cmungall** [comment]
No, all good thx!

**Comment by christabone** [comment]
@cmungall & @a8wright helped set up Travis (working well) and we now have a CONTRIBUTING.md file.
