### ISSUE TITLE
Add strand to genome location

### ISSUE THREAD

**Issue by JoelRichardson** [alliance-genome/agr_schemas#25]
Should we add strand to genomeLocation?
If so, should it be +/-? +1/-1? F/R?

**Comment by khowe** [comment]
I guess yes, for completeness. But not needed for the JBrowse link. 

How about +/-/. for forward/reverse/no-strand (a la GFF)?

**Comment by JoelRichardson** [comment]
Works for me.

**Comment by christabone** [comment]
Fixed by @sierra-moxon via commit [889bcfc](https://github.com/alliance-genome/agr_schemas/commit/889bcfce632ac54bd09d9f96525a24b4ca6bed5b).
