### ISSUE TITLE
Ambiguous prefix: GXA

### ISSUE THREAD

**Issue by cthoyt** [alliance-genome/agr_schemas#281]
The following prefix `GXA` could either refer to an experiment or a gene, therefore Identifiers.org and Prefix Commons (and therefore N2T and the Bioregistry) have minted [`gxa.expt`](https://registry.identifiers.org/registry/gxa.expt) and [`gxa.gene`](https://registry.identifiers.org/registry/gxa.gene) to differentiate. I would suggest aligning to the subspaced `gxa.expt` to avoid confusion.

https://github.com/alliance-genome/agr_schemas/blob/b6df71f4e623ae1d9316ac7d74d7d14330fdb834/resourceDescriptors.yaml#L478-L485

**Comment by christabone** [comment]
We've updated the language at the top of the README.md to indicate that this repository is no longer under active development:

https://github.com/alliance-genome/agr_schemas/blob/63bf10a58df3d68264d6e246c0cd1ce69aa0989b/README.md?plain=1#L8-L12 

We've also attempted to clarify the purpose of this repository (for resolving internally-used identifiers from our ingest pipeline and not for public-facing data or data standardization). 

The change in the README.md also points users towards our new schema directory which can be found at [agr_curation_schema ](https://github.com/alliance-genome/agr_curation_schema).
