### ISSUE TITLE
Remove decomissioned resource: Flannotator

### ISSUE THREAD

**Issue by cthoyt** [alliance-genome/agr_schemas#282]
http://www.flannotator.org.uk claims that it's permanently down. Further, the record doesn't seem to have any information on resolving identifiers from this resource, so maybe it's best to at minimum note this in the record or better, remove references to it completely.

**Comment by christabone** [comment]
We've updated the language at the top of the README.md to indicate that this repository is no longer under active development:

https://github.com/alliance-genome/agr_schemas/blob/63bf10a58df3d68264d6e246c0cd1ce69aa0989b/README.md?plain=1#L8-L12 

We've also attempted to clarify the purpose of this repository (for resolving internally-used identifiers from our ingest pipeline and not for public-facing data or data standardization). 

The change in the README.md also points users towards our new schema directory which can be found at [agr_curation_schema ](https://github.com/alliance-genome/agr_curation_schema).
