### ISSUE TITLE
Ambiguous prefix: PANTHER

### ISSUE THREAD

**Issue by cthoyt** [alliance-genome/agr_schemas#283]
The PANTHER prefix could either refer to `panther.family`, `panther.pathway`, `panther.pthcmp`, or `panther.node`. Here, it looks like `panther.family` is being used, so it would be good to normalize references to this. More information on how this prefix is used at https://bioregistry.io/registry/panther.family.

https://github.com/alliance-genome/agr_schemas/blob/b6df71f4e623ae1d9316ac7d74d7d14330fdb834/resourceDescriptors.yaml#L662-L681

**Comment by cmungall** [comment]
This is actually from the GO prefix registry, which predates identifiers.org. Note panther is part of the GO consortium. These PANTHER IDs have been used by the GOC and PANTHER for over a decade, with complete metadata about the prefix, in fact before identifiers.org existed. 

It would have been good if identifiers.org had consulted us before minting new prefixes, and it's unfortunate that bioregistry has to deal with some of these messes. I would suggest that bioregistry prioritizes authoritative sources and actual usage, but the appropriate place to discuss this is on the bioregistry tracker.
