### ISSUE TITLE
Update test example

### ISSUE THREAD

**Issue by christabone** [alliance-genome/agr_schemas#29]
With the last additions for 0.3.0 -- we need to update the test example(s) and ensure we check for every possible value.

**Comment by JoelRichardson** [comment]
Can you be more specific? I'm pretty sure "every possible value" adds up to infinity, but I'll have to check my math. ;-)

**Comment by christabone** [comment]
Haha! Sorry, every single "field" I suppose. Not necessarily the values themselves, but just a sample that tries to at least populate every field (or a file with multiple samples that cover every field).
