### ISSUE TITLE
Clarify format of IDs

### ISSUE THREAD

**Issue by cmungall** [alliance-genome/agr_schemas#4]
It's very easy for people to get confused about the format for an ID. The term "identifier" is ambiguous as to whether it includes a prefix. When people don't follow specs we end up with nightmares like `MGI:MGI:nnnn`...

In GO we have experience for cross-linking across the MODs and other databases. All IDs are global IDs in a CURIE form. The prefixes are  all registered. The local part is unique within that prefix.

Some GO-specific docs:

http://wiki.geneontology.org/index.php/Identifiers

The GO prefix registry (which is being used now by many projects beyond GO):

http://amigo.geneontology.org/xrefs

There is a YAML file anyone can make PRs against:

https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

Related PRs in this repo:

 * #2 
 * #3

**Comment by cmungall** [comment]
cc @kltm @jmcmurry

**Comment by christabone** [comment]
Related to this topic -- if we're improving the BGI schema for 0.6.0, we can add [JSON validation via regex](https://spacetelescope.github.io/understanding-json-schema/reference/regular_expressions.html) once we decide the format of primary ids.

@sierra-moxon, thoughts?

**Comment by sierra-moxon** [comment]
Please take a look at the schemas in the development branch: we will be tagging 0.6 soon with significant improvements to id format.
