### ISSUE TITLE
Support for systematic synonyms

### ISSUE THREAD

**Issue by cmungall** [alliance-genome/agr_schemas#8]
SGD and PomBase have systematic synonyms e.g. YKL106W as a special class of synonym. Will this be supported in 0.3.0?

This could be either a new field that is optional, or a special class of synonym. Currently synonym lists are string lists but post 0.3.0 we may want to move to  the obo model where synonyms are objects with provenance, type, etc.

**Comment by khowe** [comment]
WormBase too. I planned to include these in the list of general synonyms, but would prefer these to have elevated status in the list of names.

**Comment by sierra-moxon** [comment]
Agree - I brought it up at the very beginning.  We also have typed synonyms.  I am including in the list, but not itemizing.  Synonyms as objects is definitely my preference too.  for release 0.4.0, on the list for sure.

**Comment by cmungall** [comment]
I took the liberty of adding a milestone to help separate these, I assume we want to use github milestones moving forward but apologies if this has already been discussed and we decided otherwise

**Comment by christabone** [comment]
Good call, we've agreed on milestones as a group.

**Comment by christabone** [comment]
@sierra-moxon Looking over your pull request, we can probably get this into 0.3.0?

**Comment by christabone** [comment]
Resolved via video conference.
